export const speciesList = `Abarema jupunba
Acacia adhaerens
Acacia glomerosa
Acacia mangium
Acacia polyphylla
Acca sellowiana
Acioa edulis
Acioa ssp
Acosmia umnitens
Acosmium subelegans
Acrocomia aculeata
Acrodiclidium appellii
Acrodiclidium brasiliense
Acrodiclidium camara
Actinostemon ssp
Adenanthera pavonina
Affonsea bullata
Agonandra brasiliensis
Agonandra silvatica
Agonandra ssp
Aiouea saligna
Aiouea ssp
Albizia corymbosa
Albizia hasslerii
Albizia inundata
Albizia lebbeck
Albizia niopodes
Albizia pedicellaris
Albizia polycephala
Albizia ssp
Alchornea glandulosa
Alchornea sidifolia
Alchornea triplinervia
Aldina heterophylla
Alexa grandiflora
Alexa ssp
Alibertia sessilis
Allantoma decandra
Allantoma lineata
Allantoma macrocarpa
Allantoma ssp
Allophylus petiolulatus
Aloysia virgata
Amaioua guianensis
Amaioua ssp
Ambelania acida
Ambelania cuneata
Amburana acreana
Amburana cearensis
Ampelocera ruizii
Ampelocera ssp
Amphiodon effusus
Anacardium amilcorianum
Anacardium curatellaefolium
Anacardium excelsum
Anacardium giganteum
Anacardium microcarpum
Anacardium microsepalum
Anacardium negrense
Anacardium occidentale
Anacardium parvifolium
Anacardium spruceanum
Anacardium ssp
Anacardium tenuifolium
Anadenanthera colubrina
Anadenanthera falcata
Anadenanthera macrocarpa
Anadenanthera obliqua
Anadenanthera paniculata
Anadenanthera peregrina
Andira anthelmia
Andira coriacea
Andira cuiabensis
Andira fraxinifolia
Andira frondosa
Andira inermis
Andira laurifolia
Andira legalis
Andira micrantha
Andira ormosioides
Andira paniculata
Andira parviflora
Andira retusa
Andira ssp
Andira stipulacea
Andira surinamensis
Andira vermifuga
Andradea floribunda
Anemopaegma arvensis
Anemopaegma mirandum
Anemopaegma ssp
Aniba burchellii
Aniba canelilla
Aniba guianensis
Aniba parviflora
Aniba puchury-minor
Aniba riparia
Aniba rosaeodora
Aniba ssp
Aniba terminalis
Annona ambotay
Annona glabra
Annona paludosa
Annona reticulata
Annona sericea
Annona ssp
Antrocaryon amazonicum
Apeiba albiflora
Apeiba aspera
Apeiba echinata
Apeiba glabra
Apeiba hirsuta
Apeiba membranacea
Apeiba petoumo
Apeiba ssp
Apeiba tibourbou
Aptandra tubicina
Apuleia ferrea
Apuleia leiocarpa
Apuleia ssp
Arapatiella psilophylla
Aspidosperma album
Aspidosperma auriculatum
Aspidosperma carapanauba
Aspidosperma cuspa
Aspidosperma cylindrocarpon
Aspidosperma desmanthum
Aspidosperma discolor
Aspidosperma eburneum
Aspidosperma ellipsocarpum
Aspidosperma eteanum
Aspidosperma excelsum
Aspidosperma formosanum
Aspidosperma macrocarpon
Aspidosperma megalocarpon
Aspidosperma nitidum
Aspidosperma oblongifolia
Aspidosperma oblongum
Aspidosperma opulifolium
Aspidosperma pachypterum
Aspidosperma parvifolium
Aspidosperma polynesium
Aspidosperma polyneuron
Aspidosperma populifolium
Aspidosperma pyrifolium
Aspidosperma ramiflorum
Aspidosperma rigidum
Aspidosperma sandwithianum
Aspidosperma spruceanum
Aspidosperma ssp
Aspidosperma tomentosum
Aspidosperma ulei
Aspidosperma vargasii
Aspidosperma williamsii
Astronium concinnum
Astronium fraxinifolium
Astronium gracile
Astronium graveolens
Astronium lecointei
Astronium macrocalyx
Astronium ssp
Astronium ulei
Astronium urundeuva
Attalea phalerata
Bagassa guianensis
Bagassa ssp
Balfourodendron riedelianum
Balizia pedicellaris
Banara nitida
Barnebydendron riedelii
Bastardiopsis densiflora
Batesia floribunda
Bathysa meridionalis
Batocarpus ssp
Bauhinia longifolia
Bauhinia raddiana
Bauhinia rufa
Bauhinia spp
Bellucia grossularioides
Bellucia ssp
Bertholletia excelsa
Bixa arborea
Bixa orellana
Blepharocalyx salicifolius
Bocageopsis mattogrossensis
Bocageopsis multiflora
Bombacopsis glabra
Bombacopsis quinata
Bombax atenopetalum
Bombax carolinum
Bombax ceiba
Bombax coriaceum
Bombax globosum
Bombax humile
Bombax longiflorum
Bombax marginatum
Bombax munguba
Bombax paraense
Bombax pentaphyllum
Bombax spp
Bombax spruceanum
Bombax ssp
Bombax stenopetalum
Boswellia serrata
Bowdichia brasiliensis
Bowdichia major
Bowdichia nitida
Bowdichia racemosa
Bowdichia ssp
Bowdichia virgilioides
Brosimopsis oblongifolia
Brosimopsis obovata
Brosimum acutifolium
Brosimum alicastrum
Brosimum angustifolium
Brosimum galactodendron
Brosimum gaudichaudii
Brosimum guianense
Brosimum lactescens
Brosimum lanciferum
Brosimum lecointei
Brosimum paraense
Brosimum parinarioides
Brosimum petraeum
Brosimum potabile
Brosimum rubescens
Brosimum ssp
Brosimum uleanum
Brosimum utile
Buchenavia capitata
Buchenavia grandis
Buchenavia huberi
Buchenavia macrophylla
Buchenavia ochropurumna
Buchenavia parvifolia
Buchenavia ssp
Buchenavia tomentosa
Buchenavia viridiflora
Bulnesia sarmientoi
Byrsonima aerugo
Byrsonima basiloba
Byrsonima cacaophila
Byrsonima chrysophylla
Byrsonima coccolobifolia
Byrsonima crassa
Byrsonima crassifolia
Byrsonima crispa
Byrsonima densa
Byrsonima lancifolia
Byrsonima sericea
Byrsonima spicata
Byrsonima ssp
Byrsonima stipulacea
Byrsonima verbascifolia
Cabralea canjerana
Cabralea ssp
Caesalpinia echinata
Caesalpinia ferrea
Caesalpinia tinctoria
Calliandra ssp
Callisthene fasciculata
Callisthene major
Callisthene ssp
Calophyllum angulare
Calophyllum brasiliense
Calophyllum lucidum
Calophyllum ssp
Calophyllum tacamahaca
Calycophyllum acreanum
Calycophyllum spruceanum
Calycophyllum ssp
Calyptranthes clusiaefolia
Calyptranthes clusiifolia
Campomanesia guazumifolia
Campomanesia ssp
Campomanesia xanthocarpa
Campsiandra comosa
Campsiandra laurifolia
Campsiandra ssp
Capirona decorticans
Capirona huberiana
Capirona ssp
Caraipa densifolia
Caraipa excelsa
Caraipa grandifolia
Caraipa myrcioides
Caraipa paraensis
Caraipa ssp
Carapa guianensis
Carapa ssp
Cardiopetalum calophyllum
Cariniana decandra
Cariniana domestica
Cariniana estrellensis
Cariniana excelsa
Cariniana integrifolia
Cariniana legalis
Cariniana micrantha
Cariniana rubra
Cariniana ssp
Caryocar amygdaliferum
Caryocar brasiliense
Caryocar coriaceum
Caryocar crenatum
Caryocar cuneatum
Caryocar edule
Caryocar glabrum
Caryocar gracile
Caryocar microcarpum
Caryocar nuciferum
Caryocar pallidum
Caryocar spp
Caryocar ssp
Caryocar tomentosum
Caryocar villosum
Casearia decandra
Casearia gossypiosperma
Casearia javitensis
Casearia obliqua
Casearia ssp
Casearia sylvestris
Cassia adiantifolia
Cassia apoucouita
Cassia fastuosa
Cassia grandis
Cassia leiandra
Cassia multijuga
Cassia scleroxylon
Cassia spruceana
Cassia ssp
Cassipourea guianensis
Castilla ssp
Castilla ulei
Casuarina equisetifolia
Cathedra ssp
Cavanillesia arborea
Cecropia bifurcata
Cecropia catarinensis
Cecropia concolor
Cecropia glaziovi
Cecropia hololeuca
Cecropia obtusa
Cecropia pachystachya
Cecropia palmata
Cecropia paraensis
Cecropia peltata
Cecropia scabra
Cecropia sciadophylla
Cecropia ssp
Cecropia ulei
Cedrela angustifolia
Cedrela brasiliensis
Cedrela fissilis
Cedrela lilloi
Cedrela odorata
Cedrela ssp
Cedrelinga cateniformis
Cedrelinga ssp
Ceiba boliviana
Ceiba burchellii
Ceiba erianthos
Ceiba pentandra
Ceiba samauma
Ceiba speciosa
Ceiba ssp
Celtis brasiliensis
Celtis spinosa
Cenostigma macrophyllum
Cenostigma tocantinum
Centrolobium microchaete
Centrolobium paraense
Centrolobium robustum
Centrolobium ssp
Cephaelis ipecacuanha
Chamaecrista bahiae
Chamaecrista xinguensis
Chaunochiton ssp
Chimarrhis babata
Chimarrhis turbinata
Chlorophora tinctoria
Chorisia crispiflora
Chorisia insignis
Chorisia integrifolia
Chorisia pubiflora
Chorisia speciosa
Chorisia ssp
Chromolucuma rubriflora
Chrysophyllum argenteum
Chrysophyllum cainito
Chrysophyllum excelsum
Chrysophyllum gonocarpum
Chrysophyllum lucentifolium
Chrysophyllum micropholis
Chrysophyllum mucuquirana
Chrysophyllum oppositum
Chrysophyllum prieurii
Chrysophyllum sanguinolentum
Chrysophyllum sericeum
Chrysophyllum ssp
Chrysophyllum venezuelanense
Chrysophyllum viride
Cinnamomum pyrifolium
Cinnamomum zeylanicum
Citharexylum cinerium
Citronella ssp
Citrus maxima
Clarisia racemifera
Clarisia racemosa
Clarisia ssp
Clathrotropis macrocarpa
Clathrotropis nitida
Clitoria amazonicum
Clitoria fairchildiana
Clusia rosea
Clusia ssp
Cnidoscolus phyllacanthus
Coccoloba ssp
Cochlospermum ssp
Colubrina glandulosa
Connarus fulvus
Copaifera bracteata
Copaifera cordifolia
Copaifera coriacea
Copaifera duckei
Copaifera guianensis
Copaifera langsdorffii
Copaifera martii
Copaifera multijuga
Copaifera officinalis
Copaifera reticulata
Copaifera ssp
Copaifera trapezifolia
Cordea ssp
Cordia alliodora
Cordia bicolor
Cordia calocephala
Cordia ecalyculata
Cordia exaltata
Cordia fallax
Cordia gerascanthus
Cordia glabrata
Cordia goeldiana
Cordia nodosa
Cordia sagotii
Cordia scabrifolia
Cordia sellowiana
Cordia ssp
Cordia trichotoma
Cordia umbraculifera
Cordiera macrophylla
Corymbia citriodora
Couepia bracteosa
Couepia grandiflora
Couepia guianensis
Couepia leptostachya
Couepia paraensis
Couepia robusta
Couepia ssp
Couepia subcordata
Couma guianensis
Couma macrocarpa
Couma macrophylla
Couma pentaphylla
Couma rigida
Couma ssp
Couma utilis
Couratari asterotricha
Couratari glabra
Couratari guianensis
Couratari macrosperma
Couratari martiana
Couratari multiflora
Couratari oblongifolia
Couratari oligantha
Couratari pulchra
Couratari pyramidata
Couratari ssp
Couratari stellata
Couratari tauari
Couroupita guianensis
Coussapoa microcarpa
Coussarea paniculata
Coutarea hexandra
Crepidospermum rhoifolium
Croton cajucara
Croton floribundus
Croton hemiargyreus
Croton palanostigma
Croton piptocalyx
Croton salutaris
Croton ssp
Croton urucurana
Crudia oblonga
Crudia pubescens
Cryptocarya aschersoniana
Cupania longifolia
Cupania ssp
Curatella americana
Cybistax antisyphilitica
Cyclolobium ssp
Cyclolobium vecchii
Cydonia vulgaris
Cynometra bauhiniifolia
Cynometra spruceana
Dacryodes belemensis
Dacryodes sclerophylla
Dalbergia brasiliensis
Dalbergia cearensis
Dalbergia spruceana
Daphnopsis gemmiflora
Daphnopsis Mart
Deguelia hatschbachii
Dendrobangia boliviana
Dialium guianense
Dialium ssp
Dialypetalanthus fuscescens
Diatenopteryx sorbifolia
Diclinanona calycina
Dicypellium caryophyllatum
Didymopanax angustissimum
Didymopanax calvum
Didymopanax longepetiolatum
Didymopanax macrocarpum
Didymopanax morototoni
Didymopanax navarroi
Didymopanax spp
Didymopanax ssp
Dillenia indica
Dilodendron bipinnatum
Dilodendron ssp
Dimorphandra gardneriana
Dimorphandra macrostachya
Dimorphandra mollis
Dimorphandra multiflora
Dimorphandra pullei
Dimorphandra ssp
Dimorphandra wilsonii
Dinizia excelsa
Dinizia ssp
Diospyros hispida
Diospyros praetermissa
Diospyros sericea
Diplokeleba floribunda
Diploon venezuelana
Diplotropis guianensis
Diplotropis incexis
Diplotropis martiusii
Diplotropis peruviana
Diplotropis purpurea
Diplotropis racemosa
Diplotropis rodriguesii
Diplotropis ssp
Diplotropis triloba
Dipteryx alata
Dipteryx ferrea
Dipteryx magnifica
Dipteryx micrantha
Dipteryx odorata
Dipteryx polyphylla
Dipteryx punctata
Dipteryx speciosa
Dipteryx ssp
Dipteryx trifoliata
Dodecastignma ssp
Drymaria cordate
Drypetes ssp
Drypetes variabilis
Duckeodendron cestroides
Duguetia cadaverica
Duguetia flagellaris
Duguetia longifolia
Duguetia riparia
Duguetia ssp
Duroia macrophylla
Dypteryx ssp
Ecclinusa guianensis
Ecclinusa ramiflora
Ecclinusa ssp
Elaeoluma glabrescens
Emmotum fagifolium
Emmotum nitens
Endlicheria paniculata
Endlicheria sericea
Endlicheria verticillata
Endopleura uchi
Enterolobium barnebianum
Enterolobium contortisiliquum
Enterolobium ellipticum
Enterolobium gummiferum
Enterolobium maximum
Enterolobium monjolo
Enterolobium schomburgkii
Enterolobium ssp
Eperua falcata
Eperua grandiflora
Eperua oleifera
Eperua purpurea
Eperua schomburgkiana
Eperua ssp
Eremoluma williamii
Eriodendron anfractuosum
Eriotheca candolleana
Eriotheca globosa
Eriotheca gracilipes
Eriotheca longipedicellata
Eriotheca pentaphylla
Eriotheca pubescens
Eriotheca ssp
Erisma bicolor
Erisma calcaratum
Erisma fuscum
Erisma japura
Erisma lanceolatum
Erisma ssp
Erisma uncinatum
Erythrina corallodendron
Erythrina falcata
Erythrina fusca
Erythrina glauca
Erythrina mulungu
Erythrina poeppigiana
Erythrina ssp
Erythrina verna
Erythroxylum argentinum
Erythroxylum ssp
Eschweilera albiflora
Eschweilera amara
Eschweilera amazonica
Eschweilera compressa
Eschweilera coriacea
Eschweilera fracta
Eschweilera grandiflora
Eschweilera juruensis
Eschweilera longipes
Eschweilera micrantha
Eschweilera odora
Eschweilera odorata
Eschweilera ovata
Eschweilera parviflora
Eschweilera pedicellata
Eschweilera sagotiana
Eschweilera ssp
Esenbeckia febrifuga
Esenbeckia grandiflora
Esenbeckia leiocarpa
Esenbeckia ssp
Etaballia guianensis
Eucalyptus camaldulensis
Eucalyptus citriodora
Eucalyptus cloeziana
Eucalyptus grandis
Eucalyptus pellita
Eucalyptus ssp
Eucalyptus terenticornis Sm.
Eucalyptus torelliana F.Muell.
Eucalyptus urograndis
Eucalyptus urophylla
Eucalyptus urophylla S.T.Blake
Eugenia dura
Eugenia glomerata
Eugenia involucrata
Eugenia jambos
Eugenia lambertiana
Eugenia leitonii
Eugenia luschnathiana
Eugenia malaccensis
Eugenia olivacea
Eugenia rostrifolia
Eugenia ssp
Eugenia tenella
Euplassa cantareirae
Euplassa incana
Euplassa organensis
Euplassa pinnata
Euplassa ssp
Euxylophora paraensis
Fagara hymenale
Fagara kleinii
Fagara ssp
Falcataria moluccana
Ferreirea spectabilis
Ferreirea ssp
Ficus adhatodaefolia
Ficus anthelmintica
Ficus aripuanensis
Ficus blepharophylla
Ficus broadwayi
Ficus caballina
Ficus carica
Ficus castellviana
Ficus catappifolia
Ficus cestrifolia
Ficus dendrocida
Ficus enormis
Ficus eximia
Ficus frondosa
Ficus gardneriana
Ficus gomelleira
Ficus greiffiana
Ficus guaranitica
Ficus guianensis
Ficus hebetifolia
Ficus insipida
Ficus malacocarpa
Ficus matisiana
Ficus maxima
Ficus microcarpa
Ficus monckii
Ficus nymphaeifolia
Ficus obtusifolia
Ficus organensis
Ficus paraensis
Ficus pertusa
Ficus piresiana
Ficus roraimensis
Ficus sphenophylla
Ficus ssp
Ficus subtriplinervia
Ficus trigona
Ficus trigonata
Ficus vermifuga
Franchetella spp
Fusaea longifolia
Gallesia integrifolia
Gallesia ssp
Garcinia mangostana
Geissospermum laeve
Geissospermum sericeum
Geissospermum ssp
Genipa americana
Genipa caruto
Glycydendron amazonicum
Gochnatia polymorpha
Goldmania paraguensis
Gomidesia affinis
Gomidesia eriocalyx
Gomidesia ssp
Gomphia castaneaefolia
Gomphia hexasperma
Goniodiscus elaeospermus
Gouania blanchetiana
Goupia glabra
Goupia paraensis
Goupia ssp
Gualtteria olivacea
Guapira graciliflora
Guapira opposita
Guarea carinata
Guarea grandifolia
Guarea guidonia
Guarea kunthiana
Guarea macrophylla
Guarea purusana
Guarea silvatica
Guarea ssp
Guarea trichilioides
Guatteria amazonica
Guatteria citriodora
Guatteria discolor
Guatteria flava
Guatteria olivacea
Guatteria ouregou
Guatteria poeppigiana
Guatteria procera
Guatteria pubens
Guatteria sellowiana
Guatteria ssp
Guatteria vilosissima
Guazuma crinita
Guazuma tomentosa
Guazuma ulmifolia
Guettarda ssp
Guettarda viburnoides
Guibourtia hymenaefolia
Gustavia augusta
Hancornia speciosa
Handroanthus albus
Handroanthus barbatus
Handroanthus capitatus
Handroanthus chrysotrichus
Handroanthus heptaphyllus
Handroanthus impetiginosum
Handroanthus impetiginosus
Handroanthus incanus
Handroanthus ochraceus
Handroanthus pulcherrimus
Handroanthus serratifolius
Handroanthus ssp
Handroanthus umbellatus
Handroanthus vellosoi
Haploclathra paniculata
Heisteria ovata
Helicostylis pedunculata
Helicostylis podogyne
Helicostylis ssp
Helicostylis tomentosa
Helietta apiculata
Helietta longifoliata
Heliocarpus americanus
Hernandia guianensis
Hevea brasiliensis
Hevea guianensis
Hevea humilior
Hevea spruceana
Hibiscus tiliaceus
Hieronyma alchorneoides
Hieronyma ferruginea
Hieronyma laxiflora
Hieronyma ssp
Himatanthus articulatus
Himatanthus bracteatus
Himatanthus obovatus
Himatanthus phagedaenicus
Himatanthus sucuuba
Hippocratea spp
Hirtella ciliata
Hirtella eriandra
Hirtella glandulosa
Hirtella insignis
Hirtella racemosa
Hirtella ssp
Holocalyx glaziovii
Hortia arborea
Hortia excelsa
Huberodendron ingens
Huberodendron ssp
Huberodendron swietenioides
Humiria balsamifera
Humiria floribunda
Humiria ssp
Humiria strum
Hura crepitans
Hydrogaster trinervis
Hymenaea altissima
Hymenaea aurea
Hymenaea capanema
Hymenaea chapadensis
Hymenaea courbaril
Hymenaea eriogyne
Hymenaea intermedia
Hymenaea martiana
Hymenaea microphylla
Hymenaea oblongifolia
Hymenaea palustris
Hymenaea parvifolia
Hymenaea reticulata
Hymenaea rubriflora
Hymenaea splendida
Hymenaea ssp
Hymenaea stigonocarpa
Hymenolobium complicatum
Hymenolobium elatum
Hymenolobium excelsum
Hymenolobium flavum
Hymenolobium heringerianum
Hymenolobium heterocarpum
Hymenolobium modestum
Hymenolobium nitidum
Hymenolobium petraeum
Hymenolobium pulcherrimum
Hymenolobium sericeum
Hymenolobium ssp
Hyptidendron asperrimum
Ilex ssp
Inga acreana
Inga affinis
Inga alba
Inga auristella
Inga brachystachia
Inga brevialata
Inga calantha
Inga calophylla
Inga capitata
Inga cinnamomea
Inga cordatoalata
Inga cylindrica
Inga duckei
Inga edulis
Inga ferrugineo-hirta
Inga gracilifolia
Inga heterophylla
Inga inundata
Inga lanceaefolia
Inga lateriflora
Inga laurina
Inga longipedunculata
Inga macrophylla
Inga marginata
Inga nobilis
Inga obidensis
Inga paraensis
Inga polyantha
Inga quadrangularis
Inga sataremnensis
Inga semialata
Inga sertulifera
Inga sessilis
Inga setifera
Inga speciosa
Inga spixiana
Inga ssp
Inga stipularis
Inga tenuistipula
Inga thibaldiana
Inga uraguensis
Inga vera
Iriartea delvidea
Iryanthera crassifolia
Iryanthera elliptica
Iryanthera grandis
Iryanthera juruensis
Iryanthera lancifolia
Iryanthera macrophylla
Iryanthera olacoides
Iryanthera paradoxa
Iryanthera paraensis
Iryanthera polyneura
Iryanthera sagotiana
Iryanthera ssp
Iryanthera tessmannii
Iryanthera tricornis
Iryanthera ulei
Isertia hypoleuca
Jacaranda acutifolia
Jacaranda caroba
Jacaranda chapadensis
Jacaranda copaia
Jacaranda cuspidifolia
Jacaranda macrantha
Jacaranda micrantha
Jacaranda puberula
Jacaranda ssp
Jacaratia spinosa
Jambosa aquea
Joannesia heveoides
Joannesia princeps
Kielmeyera coriacea
Kielmeyera speciosa
Lacmellea arborescens
Lacmellea lactescens
Lacunaria crenata
Lacunaria jenmani
Laetia procera
Lafoensia densiflora
Lafoensia glyptocarpa
Lafoensia pacari
Lafoensia ssp
Laguncularia racemosa
Lamanonia glabra
Lamanonia speciosa
Lamanonia ternata
Lantana camara
Laplacea fruticosa
Laurus nobilis
Lecointea amazonica
Lecythis amara
Lecythis chartacea
Lecythis idatimon
Lecythis lanceolata
Lecythis lurida
Lecythis minor
Lecythis ollaria
Lecythis paraensis
Lecythis pisonis
Lecythis poiteaui
Lecythis prancei
Lecythis ssp
Lecythis usitata
Lecythis zabucajo
Licania affinis
Licania apetala
Licania egleri
Licania glabra
Licania gracilipes
Licania heteromorpha
Licania hoehnei
Licania hypoleuca
Licania impressa
Licania incana
Licania kunthiana
Licania latifolia
Licania laxiflora
Licania longistyla
Licania macrophylla
Licania membranacea
Licania micrantha
Licania microcarpa
Licania oblongifolia
Licania octandra
Licania parinarioides
Licania parviflora
Licania pruinosa
Licania puchurymajor
Licania rigida
Licania sclerophylla
Licania ssp
Licania tomentosa
Licania turiuva
Licania utilis
Licaria aritu
Licaria brasiliensis
Licaria cannella
Licaria guianensis
Licaria mahuba
Licaria puchurymajor
Licaria reitzkleiniana
Licaria rigida
Licaria ssp
Lindackeria paraensis
Lindackeria ssp
Linociera hassleriana
Lithraea brasiliensis
Lonchocarpus campestris
Lonchocarpus discolor
Lonchocarpus guilleminianus
Lonchocarpus muehlbergianus
Lonchocarpus sericeus
Lonchocarpus ssp
Lonchocarpus subglaucescens
Loxopterigium ssp
Luehea candicans
Luehea conwentzii
Luehea crispa
Luehea divaricata
Luehea grandiflora
Luehea ochrophylla
Luehea paniculata
Luehea speciosa
Luehea ssp
Lueheopsis duckeana
Lueheopsis rosea
Luetzelburgia auriculata
Luetzelburgia trialata
Mabea angustifolia
Mabea pohliana
Mabea ssp
Machaerium aculeatum
Machaerium acutifolium
Machaerium brasiliense
Machaerium glabrum
Machaerium macrophyllum
Machaerium scleroxylon
Machaerium ssp
Machaerium villosum
Maclura tinctoria
Macoubea guianensis
Macrolobium acacifolium
Macrolobium bifolium
Macrolobium brevense
Macrolobium chrysostachyum
Macrolobium latifolium
Macrolobium multijugum
Macrolobium pendulum
Macrosamanea pedicellaris
Magnolia acuminata
Magnolia grandiflora
Magnolia stellata
Malouetia cestroides
Malouetia duckei
Malouetia tamaquarina
Mangifera indica
Manilkara amazonica
Manilkara bella
Manilkara bidentata
Manilkara cavalcantei
Manilkara elata
Manilkara excelsa
Manilkara huberi
Manilkara inundata
Manilkara longifolia
Manilkara paraensis
Manilkara rufula
Manilkara salzmanni
Manilkara ssp
Manilkara subsericea
Manilkara surinamensis
Manilkara triflora
Maprounea guianensis
Maquira calophylla
Maquira coriacea
Maquira guianensis
Maquira sclerophylla
Marmaroxylon racemosum
Martiodendron elatum
Martiodendron excelsa
Martiodendron ssp
Marupa francoana
Matayba guianensis
Matisia cordata
Matisia ochrocalyx
Matisia paraensis
Matisia ssp
Mauritia aculeata
Mauritia flexuosa
Maytenus pruinosa
Maytenus ssp
Melanoxylon brauna
Melia azedarach
Melicoccus lepidopetalus
Melochia umbellata
Metrodorea nigra
Mezilaurus itauba
Mezilaurus lindaviana
Mezilaurus ssp
Mezilaurus synandra
Michelia fuscata
Miconia sellowiana
Miconia ssp
Miconia surinamensis
Micrandra elata
Micrandra rossiana
Micrandropsis scleroxylon
Micropholis acutangula
Micropholis cuspidatum
Micropholis egensis
Micropholis guyanensis
Micropholis melinoniana
Micropholis mensalis
Micropholis rigida
Micropholis ssp
Micropholis venulosa
Micropholis venunosa
Micropholis williamii
Mimusops ssp
Minquartia guianensis
Minquartia punctata
Minquartia ssp
Mollia lepidota
Mollinedia triflora
Mora paraensis
Moringa pterygosperma
Moronobea coccinea
Moronobea grandiflora
Moronobea pulchra
Moronobea ssp
Morus alba
Morus nigra
Mouriri brachyantha
Mouriri brevipes
Mouriri callocarpa
Mouriri grandiflora
Mouriri ssp
Mouriri ulei
Myrcia laevigata
Myrcia paivae
Myrcia tomentosa
Myrcia velutina
Myristica carinata
Myristica macrophylla
Myristica otoba
Myristica platysperma
Myristica uaupensis
Myrocarpus fastigiatus
Myrocarpus frondosus
Myrocarpus ssp
Myroxylon balsamum
Myroxylon peruiferum
Myroxylon ssp
Myroxylon toluifera
Myrsine oblonga
Naucleopsis macrophylla
Nectandra angustifolia
Nectandra cissiflora
Nectandra coriacea
Nectandra cuspidata
Nectandra discolor
Nectandra globosa
Nectandra grandiflora
Nectandra lanceolata
Nectandra leucothyrsus
Nectandra membranacea
Nectandra mollis
Nectandra moritziana
Nectandra nitidula
Nectandra pichurim
Nectandra puberula
Nectandra pulverulenta
Nectandra purusensis
Nectandra reticulata
Nectandra robusta
Nectandra rubra
Nectandra ssp
Nectandra warmingii
Neea oppositifolia
Neea ssp
Nemaluma anomala
Neoxythece robusta
Neoxythece ssp
Newtonia contorta
Newtonia suaveolens
Ochroma lagopus
Ochroma pyramidale
Ochroma ssp
Ocotea aciphylla
Ocotea acutangula
Ocotea acutifolia
Ocotea barcellensis
Ocotea baturitensis
Ocotea bicolor
Ocotea bracteosa
Ocotea canaliculata
Ocotea carymbosa
Ocotea catharinensis
Ocotea caudata
Ocotea cinerea
Ocotea cordata
Ocotea corymbosa
Ocotea cymbarum
Ocotea diospyrifolia
Ocotea divaricata
Ocotea fragrantissima
Ocotea glandulosa
Ocotea glaziovii
Ocotea glomerata
Ocotea grandiflora
Ocotea guianensis
Ocotea hookeriana
Ocotea indecora
Ocotea lancifolia
Ocotea leucoxylon
Ocotea megaphylla
Ocotea minarum
Ocotea neesiana
Ocotea nitidula
Ocotea odorata
Ocotea odorifera
Ocotea opifera
Ocotea pomaderroides
Ocotea porosa
Ocotea pretiosa
Ocotea prolifera
Ocotea puberula
Ocotea pubescens
Ocotea pulchella
Ocotea spectabilis
Ocotea spixiana
Ocotea splendens
Ocotea ssp
Ocotea suaveolens
Ocotea teleiandra
Ocotea variabilis
Ocotea velutina
Oenocarpus bacaba
Ogcodeia amara
Onychopetalum amazonicum
Ormosia amazonica
Ormosia arborea
Ormosia coccinea
Ormosia costulata
Ormosia coutinhoi
Ormosia cuneata
Ormosia excelsa
Ormosia flava
Ormosia heterophylla
Ormosia holerythra
Ormosia macrophylla
Ormosia melanocarpa
Ormosia nitida
Ormosia nobilis
Ormosia paraensis
Ormosia santaremnensis
Ormosia ssp
Ormosia stipularis
Osteophloeum platyspermum
Otoba parvifolia
Oxandra spp
Pachira aquatica
Pachira ssp
Parahancornia amapa
Parahancornia ssp
Parapiptadenia rigida
Paraprotium amazonicum
Paratecoma peroba
Parinari coriaceum
Parinari excelsa
Parinari montana
Parinari rodolphi
Parinari ssp
Parinarium barbatum
Parinarium excelsum
Parinarium montanum
Parinarium pajura
Parinarium rodolphi
Parkia decussata
Parkia gigantocarpa
Parkia multijuga
Parkia nitida
Parkia oppositifolia
Parkia paraensis
Parkia pendula
Parkia platycephala
Parkia ssp
Parkia ulei
Parkia velutina
Patagonula americana
Patagonula bahiensis
Pausandra densiflora
Pavonia bahiensis
Peltogyne angustiflora
Peltogyne catingae
Peltogyne confertiflora
Peltogyne densiflora
Peltogyne discolor
Peltogyne floribunda
Peltogyne lecointei
Peltogyne maranhensis
Peltogyne paniculata
Peltogyne paradoxa
Peltogyne pophyrocardia
Peltogyne recifencis
Peltogyne ssp
Peltogyne subsessilis
Peltogyne venosa
Peltophorum dubium
Pentaclethra macroloba
Pera glabrata
Peraltea erythrimaefolia
Perebea concinna
Perebea guianensis
Perebea lecointei
Perebea mollis
Persea cordata
Persea gratissima
Persea jariensis
Persea laevigata
Persea racemosa
Peschiera fuchsiaefolia
Phoebe semicarpifolia
Phyllocalyx strictus
Physocalymma scaberrimum
Phytolacca dioica
Pilocarpus jaborandi
Pimenta pseudocaryophyllus
Pinus elliottii
Piptadenia amazonica
Piptadenia communis
Piptadenia excelsa
Piptadenia foliolosa
Piptadenia gonoacantha
Piptadenia nitida
Piptadenia opacifolia
Piptadenia paniculata
Piptadenia piteroclada
Piptadenia ssp
Piptocarpha angustifolia
Piptocarpha macropoda
Piranhea trifoliata
Pisonia ssp
Pithecellobium acacioides
Pithecellobium adenophorum
Pithecellobium avaremotemo
Pithecellobium decandrum
Pithecellobium dinizii
Pithecellobium diversifolium
Pithecellobium dubium
Pithecellobium duckei
Pithecellobium edwallii
Pithecellobium elegans
Pithecellobium foliolosum
Pithecellobium inaequale
Pithecellobium incuriale
Pithecellobium langsdorffii
Pithecellobium longiramosum
Pithecellobium niopoides
Pithecellobium panurense
Pithecellobium pedicelare
Pithecellobium pubescens
Pithecellobium racemosum
Pithecellobium saman
Pithecellobium scandens
Pithecellobium ssp
Pithecellobium tortum
Pithecellobium trapezifolium
Pithecellobium unifoliolatum
Planchonella oblanceolata
Planchonella pachycarpa
Planchonella ssp
Plathymenia foliolosa
Plathymenia reticulata
Platonia insignis
Platycyamus regnellii
Platycyamus spp
Platymiscium blanchetii
Platymiscium duckei
Platymiscium filipes
Platymiscium ssp
Platymiscium trinitatis
Platymiscium ulei
Platypodium elegans
Pleurothyrium cuneifolium
Podocarpus lambertii
Podocarpus sellowii
Poecilanthe effusa
Poecilanthe grandiflora
Poecilanthe parviflora
Poeppigia procera
Pogonophora schomburgkiana
Polygonanthus amazonicus
Poraqueiba guianensis
Poupartia ssp
Pourouma aspera
Pourouma bicolor
Pourouma cecropiifolia
Pourouma guianensis
Pourouma longipendula
Pourouma minor
Pouteria anomala
Pouteria bangii
Pouteria bilocularis
Pouteria caimito
Pouteria clandantha
Pouteria cuspidata
Pouteria decorticans
Pouteria egregia
Pouteria elegans
Pouteria gongrijpii
Pouteria guianensis
Pouteria hispida
Pouteria lasiocarpa
Pouteria laurifolia
Pouteria macrocarpa
Pouteria macrophylla
Pouteria multiflora
Pouteria oblanceolata
Pouteria obtusifolia
Pouteria opposita
Pouteria oppositifolia
Pouteria pachycalyx
Pouteria pariry
Pouteria platyphylla
Pouteria procera
Pouteria ramiflora
Pouteria reticulata
Pouteria speciosa
Pouteria ssp
Pouteria torta
Pouteria venosa
Pouteria williamii
Pradosia cochlearia
Pradosia kuhlmannii
Pradosia schomburgkiana
Priogymnanthus hasslerianus
Protium almecega
Protium amazonicum
Protium apiculatum
Protium araguense
Protium brasiliense
Protium carana
Protium decandrum
Protium divaricatum
Protium duckei
Protium guacayanum
Protium heptaphyllum
Protium insigne
Protium kleinii
Protium macrophyllum
Protium nitidum
Protium paliidum
Protium paniculatum
Protium paraense
Protium paraensis
Protium puncticulatum
Protium robustum
Protium sagotianum
Protium spruceanum
Protium ssp
Protium subserratum
Protium tenuifolium
Protium trifoliolatum
Prunus armeniaca
Prunus brasiliensis
Pseudima ssp
Pseudobombax grandiflorum
Pseudobombax longiflorum
Pseudobombax munguba
Pseudobombax tomentosum
Pseudolmedia laevigata
Pseudolmedia multinervis
Pseudolmedia murure
Pseudolmedia ssp
Pseudopiptadenia psilostachya
Pseudopiptadenia suaveolens
Psidium acutangulum
Psidium aerugineum
Psidium araca
Psidium densicomum
Psidium dentale
Psidium guajava
Psidium sartorianum
Psidium ssp
Psychotria parviflora
Pterocarpus amazonicus
Pterocarpus ancylocalix
Pterocarpus ancylocalyx
Pterocarpus draco
Pterocarpus officinalis
Pterocarpus rohrii
Pterocarpus ssp
Pterocarpus violaceus
Pterodon apparicioi
Pterodon emarginatus
Pterodon pubescen
Pterodon pubescens
Pterodon Pubescens
Pterogyne nitens
Pterygota brasiliensis
Qualea acuminata
Qualea brevipedicellata
Qualea coerulea
Qualea dichotoma
Qualea dinizii
Qualea glaberrima
Qualea grandiflora
Qualea homosepala
Qualea labouriauana
Qualea lancifolia
Qualea magna
Qualea multiflora
Qualea paraensis
Qualea parviflora
Qualea speciosa
Qualea ssp
Qualea tessmannii
Qualea withobkii
Quassia amara
Randia armata
Rapanea ferruginea
Rapanea guianensis
Rapanea lactevirens
Rapanea ssp
Raputia magnifica
Rauwolfia paraensis
Rauwolfia pentaphylla
Rauwolfia ssp
Recordoxylon amazonicum
Rheedia acuminata
Rheedia brasiliensis
Rheedia floribunda
Rheedia macrophylla
Rhizophora mangle
Rhodostemonodaphne dioica
Rinorea guianensis
Rinorea macrocarpa
Rinorea ssp
Rollinia cuspidata
Rollinia exsucca
Rollinia insignis
Rollinia mucosa
Rollinia orthopetala
Rollinia salicifolia
Rollinia ssp
Roupala brasiliensis
Roupala cearensis
Roupala glabrata
Roupala montana
Roupala ssp
Roupala thomesiana
Ruizterania albiflora
Sacoglottis amazonica
Sacoglottis cuspidata
Sacoglottis guianensis
Sacoglottis mattogrossensis
Sacoglottis spp
Sacoglottis ssp
Sacoglottis uchi
Sacoglottis verrucosa
Sagotia racemosa
Salacia grandiflora
Salvertia convallariaeodora
Samanea polycephala
Samanea saman
Samanea tubulosa
Sapindus cerasinus
Sapindus esculentus
Sapindus saponaria
Sapium aereum
Sapium aucuparium
Sapium bogotense
Sapium ciliatum
Sapium glandulatum
Sapium haematospermum
Sapium hippomane
Sapium leptadenium
Sapium longifolium
Sapium marmieri
Sapium obovatum
Sapium sceleratum
Sapium ssp
Sapium taburu
Sarcaulus brasiliensis
Sarcomphalus cinnamomum
Schefflera morototoni
Schefflera paraensis
Schefflera ssp
Schinopsis brasiliensis
Schinus polygamus
Schizolobium
Schizolobium excelsum
Schizolobium parahyba
Schizolobium ssp
Sciadodendron excelsum
Sclerolobium aureum
Sclerolobium chrysophyllum
Sclerolobium denudatum
Sclerolobium eriopetalum
Sclerolobium goeldianum
Sclerolobium guianense
Sclerolobium melanocarpum
Sclerolobium melinonii
Sclerolobium paniculatum
Sclerolobium paraense
Sclerolobium ssp
Sclerolobium tinctorum
Scleronema micranthum
Scleronema praecox
Sebastiania brasiliensis
Sebastiania commersoniana
Sebastiania klotzschiana
Sebastiania membranifolia
Sebastiania schottiana
Secondatia floribunda
Securinega guarayuva
Senna multijuga
Senna spectabilis
Sessea brasiliensis
Sextonia rubra
Sickingia rubescens
Sickingia ssp
Sideroxylon obtusifolium
Sideroxylon portoricense
Silvia itauba
Simaba cuneata
Simaba guianensis
Simaba spp
Simaba subcymosa
Simarouba amara
Simarouba glauca
Simarouba ssp
Simarouba versicolor
Simira pikia
Simira rubescens
Siparuna guianensis
Siparuna ssp
Sloanea alnifolia
Sloanea brachysepala
Sloanea dentata
Sloanea eichleri
Sloanea froesii
Sloanea grandiflora
Sloanea grandis
Sloanea guianensis
Sloanea lasiocoma
Sloanea monosperma
Sloanea nitida
Sloanea ssp
Sloanea tenuiflora
Socratea exorrhiza
Spondias dulcis
Spondias lutea
Spondias mombin
Spondias purpurea
Spondias ssp
Spondias venulosa
Sterculia alata
Sterculia apeibophylla
Sterculia apetala
Sterculia chicha
Sterculia chicomendesii
Sterculia elata
Sterculia excelsa
Sterculia pilosa
Sterculia pruriens
Sterculia speciosa
Sterculia ssp
Sterculia striata
Sterigmapetalum obovatum
Strychnos pseudo-quina
Strychnos rouhamon
Stryphnodendron guianense
Stryphnodendron paniculatum
Stryphnodendron pulcherrimum
Styrax acuminatum
Styrax camporum
Styrax pohlii
Styrax ssp
Swartzia acuminata
Swartzia acutifolia
Swartzia aptera
Swartzia arborescens
Swartzia cinerea
Swartzia corrugata
Swartzia flaemingii
Swartzia fugax
Swartzia grandiflora
Swartzia grandifolia
Swartzia ingaefolia
Swartzia laevicarpa
Swartzia langsdorffii
Swartzia laurifolia
Swartzia leiocalycina
Swartzia leptopetala
Swartzia macrostachya
Swartzia oblata
Swartzia panacoco
Swartzia racemosa
Swartzia recurva
Swartzia ssp
Swartzia stipulifera
Swartzia tomentosa
Sweetia dasycarpa
Sweetia elegans
Sweetia fruticosa
Sweetia nitens
Swietenia macrophylla
Syagrus inajai
Symmeria paniculata
Symphonia globulifera
Symplocos ssp
Syzygiopsis appositifolia
Syzygiopsis opaca
Syzygiopsis oppositifolia
Syzygium aqueum
Tabebuia angustata
Tabebuia aurea
Tabebuia cassinoides
Tabebuia fluviatilis
Tabebuia roseoalba
Tachigali alba
Tachigali cavipes
Tachigali eriopetala
Tachigali multijuga
Tachigali myrmecophila
Tachigali paniculata
Tachigali paraensis
Tachigali rugosa
Tachigali ssp
Talauma ovata
Talisia acutifolia
Talisia carinata
Talisia esculenta
Talisia intermedia
Talisia megaphylla
Talisia ssp
Tamarindus indica
Tapirira guianensis
Tapirira marchandii
Tapirira obtusa
Tapirira ssp
Tapura amazonica
Taralea oppositifolia
Tectona Grandis
Tectona grandis
Terminalia actinophylla
Terminalia acuminata
Terminalia amazonia
Terminalia argentea
Terminalia brasiliensis
Terminalia catappa
Terminalia dichotoma
Terminalia fagifolia
Terminalia glabrescens
Terminalia guianensis
Terminalia januarensis
Terminalia kuhlmannii
Terminalia lucida
Terminalia obovata
Terminalia ssp
Terminalia tanibouca
Tetragastris altissima
Tetragastris cerradicola
Tetragastris grossa
Tetragastris panamensis
Tetragastris pilosa
Tetragastris ssp
Tetragastris trifoliolata
Tetrorchidium ssp
Theobroma bicolor
Theobroma grandiflorum
Theobroma martiana
Theobroma ssp
Theobroma subincanum
Theobroma sylvestris
Thuja orientalis
Thyrsodium paraense
Thyrsodium schomburgkianum
Thyrsodium spruceanum
Tipuana erythrocarpa
Toulicia guianensis
Tovomita paniculata
Tovomita speciosa
Trattinnickia burseraefolia
Trattinnickia demerarae
Trattinnickia lawrencei
Trattinnickia rhoifolia
Trattinnickia ssp
Trema micrantha
Trichilia barraensis
Trichilia catigua
Trichilia quadrijuga
Trichilia ssp
Triplaris americana
Triplaris gardneriana
Triplaris surinamensis
Unonopsis guatterioides
Vantanea cupularis
Vantanea guianensis
Vantanea paniculata
Vantanea parviflora
Vantanea ssp
Vatairea araroba
Vatairea fusca
Vatairea guianensis
Vatairea heteroptera
Vatairea macrocarpa
Vatairea paraensis
Vatairea Paraensis
Vatairea sericea
Vatairea speciosa
Vatairea ssp
Vataireopsis araroba
Vataireopsis iglesiasii
Vataireopsis speciosa
vataireopsis speciosa
Vataireopsis ssp
Virola albidiflora
Virola caducifolia
Virola calophylla
Virola calophyloidea
Virola carinata
Virola coelhoi
Virola cuspidata
Virola decorticans
Virola divergens
Virola duckei
Virola flexuosa
Virola gardneri
Virola loretensis
Virola malmei
Virola melinonii
Virola michelii
Virola minutiflora
Virola mollissima
Virola multicostata
Virola multiflora
Virola multinervia
Virola oleifera
Virola pavonis
Virola sebifera
Virola ssp
Virola surinamensis
Virola theiodora
Virola venosa
Virolae longata
Vismia brasiliensis
Vismia cayannensis
Vismia guianensis
Vismia guineensis
Vismia latifolia
Vismia parviflora
Vismia spp
Vismia ssp
Vitex cymosa
Vitex flavens
Vitex montevidensis
Vitex multinervis
Vitex orinocensis
Vitex polygama
Vitex ponshiniana
Vitex ssp
Vitex triflora
Vochysia cinnamomea
Vochysia densiflora
Vochysia divergens
Vochysia eximia
Vochysia ferruginea
Vochysia floribunda
Vochysia grandis
Vochysia guianensis
Vochysia hankeana
Vochysia inundata
Vochysia magnifica
Vochysia mapuerae
Vochysia maxima
Vochysia melinoni
Vochysia obidensis
Vochysia obscura
Vochysia oppugnata
Vochysia paraensis
Vochysia rufescens
Vochysia ssp
Vochysia surinamensis
Vochysia tucanorum
Vochysia vismiifolia
Vouacapoua americana
Vouacapoua cuiabensis
Vouacapoua pallidior
Warszewiczia coccinea
Xylopia aromatica
Xylopia benthami
Xylopia brasiliensis
Xylopia emarginata
Xylopia frutescens
Xylopia fruttescens
Xylopia nitida
Xylopia polyantha
Xylopia sericea
Xylopia ssp
Xylopia xylopioides
Zanthoxylum acreanum
Zanthoxylum hermaphroditum
Zanthoxylum regnelianum
Zanthoxylum rhoifolium
Zanthoxylum riedelianum
Zanthoxylum ssp
Zanthoxylum tuberculatum
Zeyheria tuberculosa
Zollernia ilicifolia
Zollernia paraensis
Zygia cauliflora
Zygia latifolia
Zygia racemosa
Zygia saman`