export const speciesList = `Manilkara huberi
Erisma uncinatum
Goupia glabra
Dinizia excelsa
Hymenaea courbaril
Qualea ssp
Apuleia leiocarpa
Mezilaurus itauba
Dipteryx odorata
Couratari guianensis
Qualea paraensis
Handroanthus serratifolius
Ruizterania albiflora
Hymenolobium petraeum
Schizolobium parahyba
Astronium lecointei
Hymenolobium ssp
Cedrelinga cateniformis
Cariniana micrantha
Simarouba amara
Trattinnickia burseraefolia
Trattinnickia ssp
Caryocar villosum
Apuleia ssp
Allantoma lineata
Bagassa guianensis
Clarisia racemosa
Micropholis venulosa
Couratari ssp
Dipteryx ssp
Hymenolobium excelsum
Ocotea ssp
Couratari oblongifolia
Pseudopiptadenia suaveolens
Alexa grandiflora
Enterolobium schomburgkii
Hymenaea ssp
Tachigali paniculata
Manilkara ssp
Handroanthus ssp
Peltogyne paniculata
Vochysia ssp
Bowdichia nitida
Sextonia rubra
Parkia multijuga
Chrysophyllum venezuelanense
Parkia pendula
Couratari stellata
Pouteria ssp
Cedrela odorata
Protium heptaphyllum
Enterolobium contortisiliquum
Carapa guianensis
Ceiba pentandra
Couratari tauari
Micropholis ssp
Parkia paraensis
Peltogyne lecointei
Manilkara excelsa
Pouteria caimito
Amburana acreana
Hymenolobium heterocarpum
Protium ssp
Lecythis pisonis
Parkia ssp
Qualea dinizii
Chrysophyllum lucentifolium
Terminalia amazonia
Jacaranda copaia
Castilla ulei
Tetragastris panamensis
Lecythis lurida
Vochysia maxima
Ocotea neesiana
Eucalyptus grandis
Astronium ssp
Brosimum parinarioides
Ocotea cymbarum
Caryocar glabrum
Cariniana ssp
Tachigali myrmecophila
Manilkara paraensis
Pouteria venosa
Vatairea sericea
Erisma ssp
Martiodendron elatum
Aspidosperma ssp
Hymenaea oblongifolia
Caryocar microcarpum
Pouteria pariry
Pouteria guianensis
Ocotea spixiana
Vochysia guianensis
Vatairea ssp
Sclerolobium ssp
Brosimum guianense
Peltogyne ssp
Vouacapoua americana
Eschweilera coriacea
Lecythis chartacea
Cariniana estrellensis
Eucalyptus urophylla S.T.Blake
Protium robustum
Buchenavia capitata
Schizolobium ssp
Diplotropis ssp
Buchenavia ssp
Vochysia divergens
Eperua oleifera
Hymenolobium modestum
Parkia nitida
Trattinnickia rhoifolia
Anacardium giganteum
Castilla ssp
Psidium dentale
Endopleura uchi
Eucalyptus  pellita
Andira parviflora
Terminalia tanibouca
Lecythis idatimon
Vochysia inundata
Manilkara bidentata
Astronium ulei
Vatairea guianensis
Dipteryx polyphylla
Cordia goeldiana
Hymenolobium nitidum
Dialium guianense
Aspidosperma polyneuron
Diplotropis purpurea
Machaerium macrophyllum
Hura crepitans
Peltogyne catingae
Buchenavia huberi
Handroanthus impetiginosus
Hymenolobium elatum
Ceiba ssp
Pouteria ramiflora
Chrysophyllum ssp
Brosimum ssp
Aspidosperma macrocarpon
Sclerolobium paniculatum
Buchenavia grandis
Vataireopsis speciosa
Guarea ssp
Scleronema micranthum
Eschweilera grandiflora
Copaifera multijuga
Peltogyne densiflora
Vatairea paraensis
Eucalyptus torelliana F.Muell.
Virola surinamensis
Hymenolobium complicatum
Vochysia paraensis
Manilkara inundata
Euxylophora paraensis
Enterolobium ssp
Qualea brevipedicellata
Brosimum rubescens
Couratari macrosperma
Iryanthera paraensis
Caryocar gracile
Guarea silvatica
Vatairea fusca
Eschweilera ssp
Macrolobium pendulum
Lindackeria paraensis
Qualea lancifolia
Couma ssp
Erisma calcaratum
Erisma lanceolatum
Protium sagotianum
Couepia ssp
Parkia oppositifolia
Eschweilera ovata
Tectona Grandis
Bowdichia ssp
Neoxythece robusta
Manilkara longifolia
Handroanthus impetiginosum
Eschweilera parviflora
Hymenaea parvifolia
Peltogyne subsessilis
Copaifera ssp
Sterculia alata
Protium paraense
Guarea guidonia
Copaifera guianensis
Couratari martiana
Pithecellobium ssp
Manilkara salzmanni
Hymenolobium pulcherrimum
Calophyllum brasiliense
Piptadenia gonoacantha
Chrysophyllum prieurii
Vochysia vismiifolia
Peltogyne angustiflora
Ferreirea spectabilis
Dipteryx trifoliata
Sclerolobium paraense
Handroanthus capitatus
Diplotropis racemosa
Pouteria cuspidata
Hymenolobium sericeum
Aspidosperma desmanthum
Macrolobium latifolium
Calycophyllum spruceanum
Copaifera langsdorffii
Ceiba samauma
Astronium gracile
Parahancornia amapa
Calophyllum ssp
Ocotea velutina
Triplaris surinamensis
Astronium fraxinifolium
Ocotea puberula
Piptadenia foliolosa
Albizia hasslerii
Barnebydendron riedelii
Ficus ssp
Copaifera reticulata
Enterolobium maximum
Nectandra ssp
Martiodendron ssp
Hymenaea capanema
Mezilaurus lindaviana
Manilkara amazonica
Anacardium ssp
Dipteryx speciosa
Vantanea parviflora
Andira surinamensis
Buchenavia parvifolia
Anacardium spruceanum
Licaria rigida
Protium puncticulatum
Sterculia ssp
Cedrela ssp
Qualea acuminata
Bombax ssp
Couma guianensis
Eschweilera longipes
Cordia trichotoma
Protium paniculatum
Buchenavia tomentosa
Nectandra discolor
Schefflera morototoni
Dipteryx alata
Vochysia rufescens
Brosimum angustifolium
Mezilaurus ssp
Thyrsodium schomburgkianum
Licania parinarioides
Pithecellobium edwallii
Handroanthus albus
Hevea guianensis
Erisma bicolor
Diplotropis guianensis
Copaifera duckei
Lecythis poiteaui
Moronobea pulchra
Cariniana legalis
Tectona grandis
Peltogyne paradoxa
Bowdichia virgilioides
Handroanthus barbatus
Eschweilera amazonica
Guarea macrophylla
Brosimum acutifolium
Micropholis venunosa
Bowdichia brasiliensis
Osteophloeum platyspermum
Sacoglottis guianensis
Heliocarpus americanus
Lecythis zabucajo
Brosimum lactescens
Manilkara elata
Planchonella pachycarpa
Haploclathra paniculata
Pouteria oppositifolia
Apeiba ssp
Clathrotropis macrocarpa
Protium tenuifolium
Handroanthus ochraceus
Planchonella ssp
Cassia fastuosa
Ocotea corymbosa
Couratari oligantha
Couma utilis
Brosimum paraense
Moronobea ssp
Trattinnickia lawrencei
Pseudolmedia multinervis
Sterculia speciosa
Diplotropis martiusii
Eschweilera odora
Helicostylis pedunculata
Handroanthus vellosoi
Caraipa grandifolia
Protium spruceanum
Apeiba tibourbou
Bertholletia excelsa
Vantanea cupularis
Dipteryx magnifica
Aspidosperma excelsum
Inga paraensis
Eriotheca longipedicellata
Pouteria macrophylla
Protium brasiliense
Scleronema praecox
Terminalia ssp
Trichilia ssp
Sacoglottis amazonica
Couepia robusta
Nectandra robusta
Eucalyptus urograndis
Nectandra cuspidata
Aspidosperma album
Cariniana rubra
Micropholis guyanensis
Sclerolobium denudatum
Inga ssp
Buchenavia macrophylla
Stryphnodendron guianense
Lecythis paraensis
Hymenolobium flavum
Aniba canelilla
Pithecellobium adenophorum
Iryanthera crassifolia
Brosimum uleanum
Tipuana erythrocarpa
Pouteria bilocularis
Buchenavia viridiflora
Peltogyne venosa
Dimorphandra multiflora
Mezilaurus synandra
Piptadenia ssp
Peltogyne confertiflora
Guatteria olivacea
Qualea tessmannii
Brosimum potabile
Hymenaea intermedia
Didymopanax ssp
Myroxylon balsamum
Virola cuspidata
Aspidosperma parvifolium
Capirona huberiana
Cordia sagotii
Tapirira guianensis
Couratari multiflora
Vochysia eximia
Dipteryx punctata
Allantoma decandra
Vismia brasiliensis
Licaria cannella
Ficus insipida
Vochysia obscura
Pithecellobium incuriale
Anacardium parvifolium
Nectandra lanceolata
Piptadenia paniculata
Sclerolobium guianense
Eucalyptus terenticornis Sm.
Hymenolobium heringerianum
Sapium marmieri
Symphonia globulifera
Ocotea opifera
Diploon venezuelana
Ormosia paraensis
Ocotea acutangula
Qualea homosepala
Guatteria ssp
Chrysophyllum argenteum
Ocotea barcellensis
Vantanea guianensis
Sterculia pruriens
Didymopanax morototoni
Cariniana decandra
Thyrsodium spruceanum
Virola melinonii
Hymenaea altissima
Ocotea pubescens
Andira laurifolia
Vatairea speciosa
Pouteria oblanceolata
Euplassa ssp
Anadenanthera peregrina
Dipteryx ferrea
Roupala montana
Licania tomentosa
Couma macrocarpa
Gualtteria olivacea
Sclerolobium chrysophyllum
Cecropia ssp
Ocotea odorifera
Pouteria speciosa
Callisthene major
Cariniana domestica
Manilkara surinamensis
Tetragastris altissima
Ocotea fragrantissima
Tachigali alba
Licaria aritu
Chorisia speciosa
Cabralea canjerana
Sacoglottis mattogrossensis
Handroanthus incanus
Andira anthelmia
Chorisia pubiflora
Zollernia paraensis
Bowdichia racemosa
Minquartia guianensis
Lecythis lanceolata
Andira retusa
Enterolobium ellipticum
Swietenia macrophylla
Inga quadrangularis
Didymopanax calvum
Platonia insignis
Manilkara cavalcantei
Ocotea indecora
Licaria reitzkleiniana
Pouteria hispida
Ormosia coccinea
Protium subserratum
Acrodiclidium brasiliense
Vochysia floribunda
Senna multijuga
Pseudopiptadenia psilostachya
Hevea brasiliensis
Agonandra brasiliensis
Couepia bracteosa
Pouteria anomala
Laetia procera
Eschweilera compressa
Astronium urundeuva
Sclerolobium goeldianum
Pterocarpus amazonicus
Sarcaulus brasiliensis
Sterculia chicha
Protium apiculatum
Mimusops ssp
Dipteryx micrantha
Guarea grandifolia
Cedrelinga ssp
Cordia gerascanthus
Esenbeckia ssp
Cabralea ssp
Mora paraensis
Peltogyne pophyrocardia
Pterodon pubescens
Persea gratissima
Parkia gigantocarpa
Spondias lutea
Rapanea ssp
Cedrela fissilis
Sacoglottis ssp
Piptadenia excelsa
Myroxylon peruiferum
Anacardium tenuifolium
Tamarindus indica
Lecythis ssp
Qualea grandiflora
Hymenaea stigonocarpa
Huberodendron ingens
Ormosia coutinhoi
Bastardiopsis densiflora
Rapanea lactevirens
Swartzia panacoco
Iryanthera juruensis
Brosimum gaudichaudii
Helicostylis podogyne
Dialium ssp
Sweetia nitens
Marmaroxylon racemosum
Marupa francoana
Goupia paraensis
Sclerolobium melanocarpum
Ocotea acutifolia
Helicostylis tomentosa
Ficus frondosa
Styrax camporum
Micropholis melinoniana
Handroanthus heptaphyllus
Aspidosperma spruceanum
Huberodendron swietenioides
Pterocarpus ssp
Hymenaea palustris
Licania ssp
Ocotea lancifolia
Caraipa ssp
Anacardium occidentale
Parkia ulei
Pithecellobium trapezifolium
Sterculia pilosa
Bombax humile
Eucalyptus camaldulensis
Tabebuia roseoalba
Erisma fuscum
Pinus elliottii
Apeiba albiflora
Virola duckei
Schizolobium excelsum
Maclura tinctoria
Guazuma ulmifolia
Ocotea leucoxylon
Macrosamanea pedicellaris
Inga macrophylla
Jacaranda caroba
Hymenaea splendida
Pterocarpus rohrii
Cordia fallax
Lonchocarpus sericeus
Aspidosperma vargasii
Ormosia excelsa
Stryphnodendron pulcherrimum
Guarea trichilioides
Trichilia catigua
Caryocar brasiliense
Sapium aereum
Alexa ssp
Dimorphandra ssp
Xylopia ssp
Euplassa pinnata
Lafoensia glyptocarpa
Couma macrophylla
Lindackeria ssp
Apeiba glabra
Didymopanax angustissimum
Gochnatia polymorpha
Pterodon emarginatus
Virola sebifera
Virola michelii
Eugenia leitonii
Andira inermis
Didymopanax macrocarpum
Pouteria elegans
Protium macrophyllum
Cordia glabrata
Luehea conwentzii
Cecropia sciadophylla
Cordia sellowiana
Eperua purpurea
Rollinia insignis
Aspidosperma cylindrocarpon
Pithecellobium diversifolium
Vantanea ssp
Aspidosperma tomentosum
Sacoglottis verrucosa
Nectandra globosa
Amburana cearensis
Nectandra coriacea
Virola caducifolia
Cinnamomum pyrifolium
Licania heteromorpha
Phoebe semicarpifolia
Simarouba versicolor
Albizia niopodes
Andira fraxinifolia
Vochysia surinamensis
Spondias mombin
Otoba parvifolia
Ocotea spectabilis
Terminalia argentea
Inga alba
Ormosia flava
Iryanthera grandis
Brosimum petraeum
Luehea candicans
Perebea guianensis
Couratari asterotricha
Vatairea heteroptera
Cordia bicolor
Protium araguense
Virola divergens
Inga edulis
Esenbeckia leiocarpa
Protium duckei
Ocotea glomerata
Syzygiopsis oppositifolia
Linociera hassleriana
Chlorophora tinctoria
Apeiba membranacea
Swartzia macrostachya
Aspidosperma populifolium
Bombax atenopetalum
Perebea mollis
Handroanthus umbellatus
Psidium ssp
Handroanthus chrysotrichus
Elaeoluma glabrescens
Platymiscium ssp
Anadenanthera colubrina
Caryocar ssp
Bombax globosum
Inga lateriflora
Parapiptadenia rigida
Virola carinata
Virola ssp
Ochroma ssp
Ficus matisiana
Dillenia indica
Ficus gomelleira
Vochysia grandis
Sclerolobium aureum
Nectandra reticulata
Eschweilera pedicellata
Copaifera martii
Apeiba echinata
Matisia paraensis
Nectandra moritziana
Licania octandra
Brosimum utile
Ormosia ssp
Iryanthera tessmannii
Tachigali multijuga
Macrolobium acacifolium
Albizia corymbosa
Qualea magna
Eschweilera odorata
Tabebuia aurea
Vatairea araroba
Nectandra pichurim
Hancornia speciosa
Trattinnickia demerarae
Vouacapoua cuiabensis
Aspidosperma pyrifolium
Aspidosperma discolor
Nectandra cissiflora
Terminalia lucida
Vochysia hankeana
Guarea kunthiana
Centrolobium paraense
Pisonia ssp
Bowdichia major
Croton ssp
Xylopia frutescens
Licania sclerophylla
Ocotea canaliculata
Anacardium excelsum
Bombax munguba
Vouacapoua pallidior
Swartzia ingaefolia
Sacoglottis uchi
Brosimum galactodendron
Pterocarpus officinalis
Campsiandra comosa
Protium decandrum
Polygonanthus amazonicus
Swartzia stipulifera
Euplassa organensis
Inga polyantha
Sweetia fruticosa
Sapium ciliatum
Cordia alliodora
Zanthoxylum rhoifolium
Enterolobium barnebianum
Andira ssp
Xylopia benthami
Protium insigne
Miconia surinamensis
Andira paniculata
Bombax carolinum
Luehea speciosa
Sterculia apeibophylla
Pterocarpus ancylocalyx
Byrsonima ssp
Aniba rosaeodora
Anacardium microcarpum
Aspidosperma polynesium
Virola calophylla
Parkia decussata
Hieronyma ssp
Pradosia kuhlmannii
Pterodon pubescen
Duguetia flagellaris
Aspidosperma pachypterum
Citharexylum cinerium
Brosimum alicastrum
Carapa ssp
Chorisia integrifolia
Acacia mangium
Bombacopsis quinata
Aspidosperma megalocarpon
Lonchocarpus muehlbergianus
Sebastiania brasiliensis
Inga nobilis
Piranhea trifoliata
Micropholis egensis
Schefflera paraensis
Copaifera coriacea
Simaba cuneata
Copaifera bracteata
Cecropia obtusa
Bombax pentaphyllum
Anemopaegma mirandum
Micropholis williamii
Tachigali ssp
Licania glabra
Aniba parviflora
Piptocarpha macropoda
Qualea multiflora
Spondias dulcis
Aldina heterophylla
Actinostemon ssp
Theobroma ssp
Inga obidensis
Tetragastris grossa
Erythrina mulungu
Cupania ssp
Guatteria amazonica
Sapium bogotense
Aniba terminalis
Humiria ssp
Eschweilera sagotiana
Ficus trigona
Alchornea triplinervia
Humiria balsamifera
Geissospermum sericeum
Pithecellobium pedicelare
Peltophorum dubium
Rauwolfia paraensis
Vochysia melinoni
Caryocar amygdaliferum
Buchenavia ochropurumna
Campomanesia xanthocarpa
Pleurothyrium cuneifolium
Sterculia apetala
Protium paliidum
Patagonula bahiensis
Manilkara bella
Rollinia exsucca
Anadenanthera paniculata
Eriotheca ssp
Hieronyma laxiflora
Sebastiania klotzschiana
Lonchocarpus ssp
Protium almecega
Cariniana integrifolia
Micrandra rossiana
Tovomita paniculata
Newtonia suaveolens
Mauritia aculeata
Terminalia kuhlmannii
Callisthene ssp
Virola oleifera
Newtonia contorta
Ecclinusa guianensis
Myrocarpus frondosus
Couratari pyramidata
Aniba burchellii
Helicostylis ssp
Tabebuia angustata
Calophyllum lucidum
Vatairea Paraensis
Andira legalis
Persea laevigata
Ceiba boliviana
Maytenus ssp
Virola minutiflora
Moronobea coccinea
Pouteria torta
Vochysia obidensis
Ocotea nitidula
Lecointea amazonica
Sterculia striata
Amaioua guianensis
Ochroma pyramidale
Dinizia ssp
Ocotea aciphylla
Sterigmapetalum obovatum
Annona sericea
Joannesia heveoides
Zygia saman
Luehea ssp
Lantana camara
Eschweilera micrantha
Pterocarpus violaceus
Luehea grandiflora
Micropholis cuspidatum
Ficus maxima
Roupala brasiliensis
Goupia ssp
Ficus nymphaeifolia
Chrysophyllum micropholis
Dimorphandra gardneriana
Simarouba glauca
Cenostigma tocantinum
Vatairea macrocarpa
Malouetia tamaquarina
Humiria floribunda
Simaba guianensis
Pavonia bahiensis
Chrysophyllum sanguinolentum
Centrolobium microchaete
Maquira coriacea
Vataireopsis iglesiasii
Licania kunthiana
Vismia latifolia
Couepia grandiflora
Cordia ssp
Fagara ssp
Eremoluma williamii
Tetragastris ssp
Ficus aripuanensis
Terminalia acuminata
vataireopsis speciosa
Vataireopsis araroba
Diplokeleba floribunda
Caesalpinia ferrea
Astronium graveolens
Pithecellobium elegans
Poecilanthe effusa
Ocotea pretiosa
Aiouea saligna
Samanea polycephala
Aspidosperma eteanum
Virola multicostata
Anemopaegma ssp
Luehea divaricata
Ceiba burchellii
Pachira aquatica
Caryocar edule
Onychopetalum amazonicum
Qualea withobkii
Ocotea bracteosa
Bombax ceiba
Sloanea dentata
Diatenopteryx sorbifolia
Aspidosperma formosanum
Talisia esculenta
Eschweilera albiflora
Capirona ssp
Virola venosa
Manilkara triflora
Handroanthus pulcherrimus
Virola albidiflora
Eschweilera juruensis
Pseudolmedia ssp
Sclerolobium melinonii
Vochysia ferruginea
Pentaclethra macroloba
Cedrela angustifolia
Ormosia arborea
Duguetia longifolia
Eugenia ssp
Tabebuia cassinoides
Sclerolobium tinctorum
Anacardium negrense
Holocalyx glaziovii
Dimorphandra mollis
Dacryodes sclerophylla
Talisia ssp
Dialypetalanthus fuscescens
Tabebuia fluviatilis
Qualea labouriauana
Xylopia brasiliensis
Endlicheria paniculata
Psidium araca
Pouteria opposita
Couepia leptostachya
Casearia ssp
Sapium longifolium
Vochysia oppugnata
Talisia acutifolia
Ocotea caudata
Inga lanceaefolia
Melanoxylon brauna
Licania micrantha
Pouteria lasiocarpa
Licaria brasiliensis
Ocotea diospyrifolia
Machaerium scleroxylon
Dicypellium caryophyllatum
Pithecellobium racemosum
Ficus hebetifolia
Erythrina ssp
Trichilia barraensis
Sebastiania commersoniana
Brosimum lanciferum
Annona ssp
Xylopia nitida
Erythrina falcata
Virola multiflora
Jacaranda macrantha
Chrysophyllum viride
Eriotheca candolleana
Platymiscium duckei
Vochysia tucanorum
Parinari excelsa
Ocotea megaphylla
Diplotropis triloba
Licania latifolia
Xylopia aromatica
Platymiscium ulei
Erythrina corallodendron
Sweetia elegans
Iryanthera tricornis
Esenbeckia grandiflora
Pithecellobium scandens
Nectandra rubra
Ficus caballina
Caryocar pallidum
Martiodendron excelsa
Anacardium microsepalum
Croton cajucara
Lonchocarpus guilleminianus
Byrsonima crassifolia
Hymenaea martiana
Calycophyllum acreanum
Andira vermifuga
Anacardium curatellaefolium
Eucalyptus citriodora
Schizolobium
Ficus enormis
Aspidosperma williamsii
Dimorphandra wilsonii
Gallesia ssp
Anemopaegma arvensis
Caraipa densifolia
Platymiscium trinitatis
Vantanea paniculata
Tetragastris cerradicola
Bombax longiflorum
Aspidosperma ulei
Pithecellobium saman
Huberodendron ssp
Ficus carica
Ficus eximia
Sclerolobium eriopetalum
Qualea coerulea
Emmotum fagifolium
Terminalia obovata
Abarema jupunba
Iryanthera macrophylla
Ficus catappifolia
Cecropia paraensis
Apeiba aspera
Ormosia nobilis
Eperua schomburgkiana
Parinari montana
Ormosia cuneata
Sloanea grandis
Bulnesia sarmientoi
Swartzia flaemingii
Himatanthus articulatus
Inga speciosa
Clathrotropis nitida
Pterodon apparicioi
Virola theiodora
Pourouma longipendula
Sapium glandulatum
Styrax acuminatum
Cassia ssp
Cariniana excelsa
Andira stipulacea
Hymenaea aurea
Virola pavonis
Virola mollissima
Ogcodeia amara
Lueheopsis rosea
Aspidosperma cuspa
Macrolobium brevense
Protium paraensis
Chrysophyllum cainito
Himatanthus sucuuba
Pterogyne nitens
Casearia sylvestris
Licania macrophylla
Silvia itauba
Humiria strum
Himatanthus obovatus
Aloysia virgata
Sickingia ssp
Vitex ponshiniana
Ormosia amazonica
Guatteria poeppigiana
Glycydendron amazonicum
Syzygiopsis appositifolia
Micropholis acutangula
Caryocar tomentosum
Pterocarpus draco
Sapium ssp
Platypodium elegans
Allantoma ssp
Tachigali eriopetala
Parinari rodolphi
Lacmellea lactescens
Iryanthera paradoxa
Ocotea baturitensis
Ficus castellviana
Lafoensia pacari
Licania laxiflora
Bocageopsis mattogrossensis
Chaunochiton ssp
Rollinia ssp
Pourouma guianensis
Cordia nodosa
Cassia scleroxylon
Eugenia jambos
Roupala glabrata
Sarcomphalus cinnamomum
Pouteria procera
Ficus roraimensis
Aspidosperma carapanauba
Bixa arborea
Ampelocera ruizii
Maquira sclerophylla
Guatteria citriodora
Lacmellea arborescens
Pouteria egregia
Andira frondosa
Xylopia emarginata
Pseudobombax grandiflorum
Ficus greiffiana
Enterolobium monjolo
Triplaris americana
Erythroxylum argentinum
Bombax marginatum
Casearia gossypiosperma
Vitex ssp
Lithraea brasiliensis
Licania rigida
Terminalia guianensis
Pouteria macrocarpa
Ceiba speciosa
Cecropia peltata
Peltogyne discolor
Myrcia tomentosa
Caryocar coriaceum
Isertia hypoleuca
Coutarea hexandra
Anadenanthera falcata
Couepia guianensis
Parinarium barbatum
Terminalia glabrescens
Caraipa paraensis
Cordia umbraculifera
Vismia ssp
Chrysophyllum sericeum
Moronobea grandiflora
Diclinanona calycina
Euplassa incana
Tetragastris trifoliolata
Mouriri brevipes
Swartzia recurva
Nectandra angustifolia
Anadenanthera macrocarpa
Pradosia schomburgkiana
Cordia ecalyculata
Parinari coriaceum
Virola decorticans
Byrsonima verbascifolia
Vochysia mapuerae
Pterodon Pubescens
Albizia ssp
Vitex polygama
Ficus malacocarpa
Platymiscium filipes
Inga duckei
Ocotea carymbosa
Mouriri brachyantha
Ocotea guianensis
Eperua ssp
Hymenaea reticulata
Pithecellobium dubium
Attalea phalerata
Pithecellobium avaremotemo
Iryanthera sagotiana
Campsiandra ssp
Licaria ssp
Ocotea odorata
Vitex triflora
Vochysia densiflora
Aspidosperma ellipsocarpum
Croton urucurana
Ocotea glaziovii
Sapium sceleratum
Piptadenia opacifolia
Macoubea guianensis
Lecythis ollaria
Myrcia velutina
Ficus sphenophylla
Aspidosperma eburneum
Terminalia dichotoma
Swartzia aptera
Byrsonima lancifolia
Hieronyma ferruginea
Licania microcarpa
Magnolia stellata
Parkia velutina
Parkia platycephala
Swartzia corrugata
Cupania longifolia
Virola loretensis
Nectandra puberula
Perebea lecointei
Taralea oppositifolia
Chimarrhis babata
Pseudobombax munguba
Licania apetala
Zanthoxylum acreanum
Dimorphandra macrostachya
Andira cuiabensis
Inga cylindrica
Talisia megaphylla
Inga acreana
Rollinia mucosa
Hymenaea chapadensis
Cavanillesia arborea
Inga longipedunculata
Poupartia ssp
Dalbergia spruceana
Pouteria obtusifolia
Bombax coriaceum
Eperua falcata
Couratari pulchra
Couroupita guianensis
Dilodendron bipinnatum
Centrolobium ssp
Iryanthera ssp
Aniba ssp
Sloanea ssp
Triplaris gardneriana
Apeiba hirsuta
Cedrela brasiliensis
Tachigali rugosa
Erythrina fusca
Inga ferrugineo-hirta
Terminalia actinophylla
Spondias ssp
Simaba subcymosa
Sloanea lasiocoma
Crudia oblonga
Simira rubescens
Ampelocera ssp
Astronium macrocalyx
Ocotea splendens
Qualea dichotoma
Unonopsis guatterioides
Iryanthera lancifolia
Aspidosperma opulifolium
Sebastiania schottiana
Ilex ssp
Machaerium brasiliense
Balfourodendron riedelianum
Ficus obtusifolia
Ficus guianensis
Alchornea sidifolia
Lamanonia ternata
Protium amazonicum
Swartzia cinerea
Syzygium aqueum
Licania egleri
Inga affinis
Erythroxylum ssp
Ocotea teleiandra
Copaifera trapezifolia
Aniba puchury-minor
Maprounea guianensis
Gallesia integrifolia
Samanea tubulosa
Capirona decorticans
Lecythis prancei
Aiouea ssp
Ocotea cordata
Vitex orinocensis
Pseudima ssp
Aptandra tubicina
Ficus blepharophylla
Spondias purpurea
Michelia fuscata
Trichilia quadrijuga
Poecilanthe parviflora
Eschweilera amara
Ocotea pomaderroides
Diplotropis rodriguesii
Rhizophora mangle
Magnolia grandiflora
Pithecellobium langsdorffii
Sloanea nitida
Byrsonima spicata
Parinarium pajura
Tapirira obtusa
Calycophyllum ssp
Eschweilera fracta
Matisia cordata
Inga semialata
Euplassa cantareirae
Guatteria sellowiana
Bombax paraense
Eugenia involucrata
Laguncularia racemosa
Coccoloba ssp
Blepharocalyx salicifolius
Iryanthera elliptica
Manilkara rufula
Cassia multijuga
Dalbergia cearensis
Physocalymma scaberrimum
Licaria mahuba
Psidium densicomum
Ormosia nitida
Terminalia fagifolia
Magnolia acuminata
Ocotea suaveolens
Kielmeyera speciosa
Jacaranda ssp
Planchonella oblanceolata
Lamanonia speciosa
Persea cordata
Protium nitidum
Vismia parviflora
Myroxylon ssp
Cassia apoucouita
Poraqueiba guianensis
Drypetes variabilis
Swartzia leptopetala
Plathymenia reticulata
Lonchocarpus discolor
Plathymenia foliolosa
Allantoma macrocarpa
Xylopia sericea
Hymenaea microphylla
Eugenia luschnathiana
Inga capitata
Ficus subtriplinervia
Fusaea longifolia
Andira micrantha
Corymbia citriodora
Ficus piresiana
Cassia adiantifolia
Mouriri ulei
Parinari ssp
Vitex cymosa
Byrsonima chrysophylla
Lueheopsis duckeana
Balizia pedicellaris
Andira coriacea
Hirtella eriandra
Drymaria cordate
Moringa pterygosperma
Pradosia cochlearia
Rheedia floribunda
Inga uraguensis
Pouteria williamii
Piptadenia nitida
Caryocar spp
Hirtella ssp
Curatella americana
Parinarium excelsum
Iryanthera olacoides
Albizia polycephala
Swartzia langsdorffii
Dendrobangia boliviana
Micrandropsis scleroxylon
Ficus vermifuga
Loxopterigium ssp
Pogonophora schomburgkiana
Vismia cayannensis
Micropholis mensalis
Ficus paraensis
Allophylus petiolulatus
Ficus guaranitica
Calyptranthes clusiaefolia
Guatteria ouregou
Brosimum lecointei
Morus nigra
Swartzia ssp
Luehea crispa
Rauwolfia pentaphylla
Luehea paniculata
Drypetes ssp
Zygia cauliflora
Inga gracilifolia
Secondatia floribunda
Eriotheca globosa
Vataireopsis ssp
Byrsonima aerugo
Chorisia insignis
Ocotea variabilis
Ficus anthelmintica
Esenbeckia febrifuga
Licania impressa
Iryanthera polyneura
Cecropia palmata
Hydrogaster trinervis
Samanea saman
Vismia guianensis
Myrocarpus fastigiatus
Ficus gardneriana
Sloanea froesii
Piptadenia amazonica
Ambelania cuneata
Albizia inundata
Sideroxylon obtusifolium
Ficus broadwayi
Inga marginata
Aspidosperma auriculatum
Licania hypoleuca
Pouteria bangii
Couepia subcordata
Cecropia pachystachya
Lonchocarpus campestris
Licania utilis
Randia armata
Maquira calophylla
Pourouma aspera
Cordia exaltata
Falcataria moluccana
Peltogyne maranhensis
Clarisia ssp
Rapanea ferruginea
Licania membranacea
Hieronyma alchorneoides
Hibiscus tiliaceus
Virola coelhoi
Hymenaea eriogyne
Laurus nobilis
Cordiera macrophylla
Eucalyptus cloeziana
Chrysophyllum mucuquirana
Acacia polyphylla
Lafoensia densiflora
Crudia pubescens
Jacaranda micrantha
Bocageopsis multiflora
Pouteria laurifolia
Piptocarpha angustifolia
Batocarpus ssp
Inga stipularis
Dilodendron ssp
Inga laurina
Hirtella glandulosa
Sebastiania membranifolia
Neea oppositifolia
Micropholis rigida
Styrax ssp
Sloanea monosperma
Ormosia macrophylla
Minquartia ssp
Jacaranda acutifolia
Amaioua ssp
Diospyros sericea
Thuja orientalis
Byrsonima densa
Psidium guajava
Gomphia castaneaefolia
Inga brevialata
Melia azedarach
Swartzia racemosa
Ocotea divaricata
Sloanea brachysepala
Inga vera
Byrsonima stipulacea
Micrandra elata
Sapium aucuparium
Cordia calocephala
Annona glabra
Pithecellobium foliolosum
Couma pentaphylla
Perebea concinna
Agonandra ssp
Pera glabrata
Duroia macrophylla
Hippocratea spp
Swartzia tomentosa
Swartzia grandifolia
Chimarrhis turbinata
Dypteryx ssp
Campsiandra laurifolia
Goniodiscus elaeospermus
Iriartea delvidea
Eriotheca pubescens
Sterculia excelsa
Paratecoma peroba
Aspidosperma rigidum
Psidium acutangulum
Bixa orellana
Cassia leiandra
Naucleopsis macrophylla
Inga brachystachia
Andira ormosioides
Affonsea bullata
Mouriri ssp
Schinus polygamus
Roupala ssp
Hevea spruceana
Inga calophylla
Fagara hymenale
Ormosia heterophylla
Acacia adhaerens
Licania gracilipes
Nectandra purusensis
Rhodostemonodaphne dioica
Campomanesia ssp
Pithecellobium tortum
Talisia intermedia
Pouteria pachycalyx
Ecclinusa ramiflora
Recordoxylon amazonicum
Sapindus esculentus
Sideroxylon portoricense
Albizia lebbeck
Pithecellobium dinizii
Persea jariensis
Licania turiuva
Sloanea eichleri
Cassia grandis
Kielmeyera coriacea
Pithecellobium decandrum
Copaifera cordifolia
Theobroma bicolor
Ferreirea ssp
Sapindus saponaria
Cordea ssp
Mabea pohliana
Pouteria gongrijpii
Cynometra spruceana
Helietta apiculata
Vochysia magnifica
Rinorea guianensis
Tachigali cavipes
Mabea angustifolia
Cecropia ulei
Theobroma sylvestris
Hernandia guianensis
Lecythis usitata
Enterolobium gummiferum
Zygia racemosa
Talisia carinata
Sterculia chicomendesii
Pithecellobium niopoides
Psidium sartorianum
Cordia scabrifolia
Platymiscium blanchetii
Sloanea grandiflora
Cedrela lilloi
Acioa edulis
Eperua grandiflora
Peltogyne recifencis
Dacryodes belemensis
Patagonula americana
Sapium leptadenium
Callisthene fasciculata
Inga tenuistipula
Licaria guianensis
Zollernia ilicifolia
Ocotea catharinensis
Guazuma tomentosa
Prunus brasiliensis
Rheedia macrophylla
Ambelania acida
Cnidoscolus phyllacanthus
Aspidosperma ramiflorum
Sagotia racemosa
Ochroma lagopus
Geissospermum laeve
Protium carana
Bombacopsis glabra
Aspidosperma oblongifolia
Endlicheria sericea
Nectandra membranacea
Licaria puchurymajor
Ecclinusa ssp
Nectandra pulverulenta
Theobroma grandiflorum
Tetragastris pilosa
Lonchocarpus subglaucescens
Qualea speciosa
Bombax spp
Etaballia guianensis
Securinega guarayuva
Morus alba
Malouetia cestroides
Inga auristella
Ficus pertusa
Qualea glaberrima
Lacunaria crenata
Piptadenia communis
Virola calophyloidea
Siparuna guianensis
Cinnamomum zeylanicum
Colubrina glandulosa
Alibertia sessilis
Sessea brasiliensis
Myristica platysperma
Ormosia melanocarpa
Pithecellobium acacioides
Ficus organensis
Manilkara subsericea
Byrsonima basiloba
Swartzia grandiflora
Cryptocarya aschersoniana
Swartzia laevicarpa
Acioa ssp
Casearia decandra
Couratari glabra
Virola gardneri
Poeppigia procera
Swartzia arborescens
Erisma japura
Geissospermum ssp
Guarea purusana
Protium divaricatum
Daphnopsis gemmiflora
Pterygota brasiliensis
Machaerium ssp
Clusia ssp
Hortia excelsa
Piptadenia piteroclada
Vismia guineensis
Zanthoxylum ssp
Apuleia ferrea
Matisia ssp
Myristica otoba
Bagassa ssp
Simaba spp
Eriotheca pentaphylla
Neoxythece ssp
Syzygiopsis opaca
Pseudobombax longiflorum
Inga cordatoalata
Machaerium villosum
Machaerium aculeatum
Antrocaryon amazonicum
Bauhinia rufa
Sweetia dasycarpa
Licania incana
Acosmium subelegans
Inga cinnamomea
Guazuma crinita
Peltogyne floribunda
Pithecellobium duckei
Pouteria decorticans
Xylopia xylopioides
Nectandra leucothyrsus
Duguetia ssp
Pouteria reticulata
Rollinia salicifolia
Pithecellobium panurense
Vitex montevidensis
Chromolucuma rubriflora
Simira pikia
Strychnos pseudo-quina
Eriodendron anfractuosum
Chrysophyllum excelsum
Stryphnodendron paniculatum
Sacoglottis cuspidata
Gouania blanchetiana
Cybistax antisyphilitica
Erythrina glauca
Cecropia scabra
Diospyros hispida
Miconia ssp
Deguelia hatschbachii
Tovomita speciosa
Roupala thomesiana
Tapirira ssp
Guatteria discolor
Platycyamus regnellii
Duckeodendron cestroides
Inga spixiana
Ficus monckii
Diplotropis incexis
Malouetia duckei
Ficus cestrifolia
Hymenaea rubriflora
Acosmia umnitens
Genipa caruto
Podocarpus sellowii
Myroxylon toluifera
Protium guacayanum
Pseudolmedia laevigata
Goldmania paraguensis
Licania pruinosa
Pourouma cecropiifolia
Annona paludosa
Eugenia lambertiana
Byrsonima crispa
Bauhinia spp
Nemaluma anomala
Laplacea fruticosa
Crepidospermum rhoifolium
Erythrina poeppigiana
Cynometra bauhiniifolia
Erythrina verna
Pterocarpus ancylocalix
Hirtella insignis
Hyptidendron asperrimum
Pouteria clandantha
Coussarea paniculata
Mangifera indica
Syagrus inajai
Styrax pohlii
Eriotheca gracilipes
Strychnos rouhamon
Ocotea grandiflora
Fagara kleinii
Casearia javitensis
Pithecellobium inaequale
Zanthoxylum riedelianum
Apeiba petoumo
Ocotea prolifera
Peraltea erythrimaefolia
Campomanesia guazumifolia
Ocotea hookeriana
Lafoensia ssp
Licania affinis
Zanthoxylum regnelianum
Matisia ochrocalyx
Tapura amazonica
Qualea parviflora
Caryocar crenatum
Calophyllum tacamahaca
Bellucia ssp
Poecilanthe grandiflora
Schinopsis brasiliensis
Croton piptocalyx
Maytenus pruinosa
Diplotropis peruviana
Bauhinia raddiana
Sapium obovatum
Pithecellobium longiramosum
Virola malmei
Emmotum nitens
Ocotea pulchella
Licania longistyla
Agonandra silvatica
Zeyheria tuberculosa
Anacardium amilcorianum
Cardiopetalum calophyllum
Zanthoxylum hermaphroditum
Croton salutaris
Schefflera ssp
Ocotea bicolor
Albizia pedicellaris
Bauhinia longifolia
Cecropia glaziovi
Licania parviflora
Guarea carinata
Joannesia princeps
Ficus dendrocida
Gomphia hexasperma
Cassia spruceana
Rheedia brasiliensis
Parinarium montanum
Jacaratia spinosa
Caraipa myrcioides
Prunus armeniaca
Acrocomia aculeata
Chorisia ssp
Hevea humilior
Swartzia fugax
Acca sellowiana
Machaerium acutifolium
Didymopanax longepetiolatum
Cenostigma macrophyllum
Inga sessilis
Thyrsodium paraense
Ceiba erianthos
Pilocarpus jaborandi
Himatanthus bracteatus
Sloanea alnifolia
Jacaranda chapadensis
Clitoria fairchildiana
Chrysophyllum gonocarpum
Eucalyptus ssp
Roupala cearensis
Hortia arborea
Jacaranda puberula
Banara nitida
Pithecellobium pubescens
Helietta longifoliata
Eugenia malaccensis
Ormosia holerythra
Aspidosperma nitidum
Sapium haematospermum
Centrolobium robustum
Pouteria platyphylla
Myristica uaupensis
Bombax spruceanum
Protium trifoliolatum
Sickingia rubescens
Ficus trigonata
Gomidesia eriocalyx
Sterculia elata
Luetzelburgia auriculata
Adenanthera pavonina
Celtis spinosa
Guatteria pubens
Sapindus cerasinus
Annona ambotay
Daphnopsis Mart
Mouriri callocarpa
Bombax stenopetalum
Inga heterophylla
Byrsonima coccolobifolia
Rinorea macrocarpa
Licania hoehnei
Brosimopsis obovata
Guapira graciliflora
Theobroma martiana
Nectandra nitidula
Didymopanax spp
Genipa americana
Rapanea guianensis
Croton palanostigma
Licania oblongifolia
Bellucia grossularioides
Eugenia olivacea
Couma rigida
Mollinedia triflora
Raputia magnifica
Peschiera fuchsiaefolia
Caryocar cuneatum
Zygia latifolia
Hirtella racemosa
Clusia rosea
Eugenia rostrifolia
Tachigali paraensis
Sloanea tenuiflora
Coussapoa microcarpa
Ocotea porosa
Aspidosperma oblongum
Priogymnanthus hasslerianus
Terminalia brasiliensis
Salvertia convallariaeodora
Virolae longata
Myrocarpus ssp
Ocotea minarum
Swartzia acutifolia
Tetrorchidium ssp
Pithecellobium unifoliolatum
Endlicheria verticillata
Chrysophyllum oppositum
Cyclolobium vecchii
Phyllocalyx strictus
Myrcia laevigata
Terminalia catappa
Jacaranda cuspidifolia
Pouteria multiflora
Aspidosperma sandwithianum
Rollinia orthopetala
Eugenia glomerata
Sloanea guianensis
Eucalyptus urophylla
Salacia grandiflora
Platycyamus spp
Celtis brasiliensis
Cecropia hololeuca
Metrodorea nigra
Swartzia leiocalycina
Eugenia tenella
Paraprotium amazonicum
Casuarina equisetifolia
Ormosia costulata
Virola flexuosa
Inga calantha
Swartzia laurifolia
Cydonia vulgaris
Pausandra densiflora
Lecythis amara
Diospyros praetermissa
Maquira guianensis
Guatteria vilosissima
Pimenta pseudocaryophyllus
Guatteria flava
Ocotea glandulosa
Chamaecrista xinguensis
Mollia lepidota
Byrsonima crassa
Zanthoxylum tuberculatum
Guettarda ssp
Protium kleinii
Chorisia crispiflora
Pourouma minor
Caryocar nuciferum
Neea ssp
Pseudolmedia murure
Byrsonima cacaophila
Caesalpinia echinata
Clarisia racemifera
Caesalpinia tinctoria
Casearia obliqua
Nectandra mollis
Lacunaria jenmani
Nectandra warmingii
Cecropia catarinensis
Bathysa meridionalis
Cochlospermum ssp
Machaerium glabrum
Calophyllum angulare
Croton hemiargyreus
Socratea exorrhiza
Oxandra spp
Warszewiczia coccinea
Persea racemosa
Virola multinervia
Gomidesia ssp
Sapium taburu
Didymopanax navarroi
Mauritia flexuosa
Alchornea glandulosa
Terminalia januarensis
Inga setifera
Matayba guianensis
Trema micrantha
Licania puchurymajor
Pourouma bicolor
Symplocos ssp
Minquartia punctata
Guettarda viburnoides
Rinorea ssp
Talauma ovata
Lecythis minor
Iryanthera ulei
Myristica carinata
Duguetia riparia
Simarouba ssp
Ficus microcarpa
Cecropia concolor
Heisteria ovata
Guibourtia hymenaefolia
Acacia glomerosa
Cassipourea guianensis
Vitex multinervis
Podocarpus lambertii
Arapatiella psilophylla
Macrolobium chrysostachyum
Guapira opposita
Pachira ssp
Acrodiclidium camara
Melicoccus lepidopetalus
Boswellia serrata
Astronium concinnum
Siparuna ssp
Sciadodendron excelsum
Ormosia santaremnensis
Dodecastignma ssp
Luehea ochrophylla
Rollinia cuspidata
Cephaelis ipecacuanha
Rauwolfia ssp
Duguetia cadaverica
Brosimopsis oblongifolia
Copaifera officinalis
Caraipa excelsa
Gustavia augusta
Ficus adhatodaefolia
Mabea ssp
Cyclolobium ssp
Melochia umbellata
Parahancornia ssp
Aniba riparia
Couepia paraensis
Vochysia cinnamomea
Inga sertulifera
Inga sataremnensis
Batesia floribunda
Gomidesia affinis
Ormosia stipularis
Anadenanthera obliqua
Amphiodon effusus
Myristica macrophylla
Oenocarpus bacaba
Theobroma subincanum
Cathedra ssp
Calliandra ssp
Toulicia guianensis
Rheedia acuminata
Psychotria parviflora
Tapirira marchandii
Parinarium rodolphi
Senna spectabilis
Phytolacca dioica
Citrus maxima
Byrsonima sericea
Luetzelburgia trialata
Andradea floribunda
Lamanonia glabra
Spondias venulosa
Inga inundata
Vismia spp
Citronella ssp
Garcinia mangostana
Inga thibaldiana
Miconia sellowiana
Macrolobium bifolium
Annona reticulata
Cecropia bifurcata
Sacoglottis spp
Xylopia polyantha
Sapium hippomane
Jambosa aquea
Franchetella spp
Swartzia acuminata
Acrodiclidium appellii
Eugenia dura
Hirtella ciliata
Dalbergia brasiliensis
Connarus fulvus
Vitex flavens
Clitoria amazonicum
Quassia amara
Himatanthus phagedaenicus
Myrsine oblonga
Chamaecrista bahiae
Nectandra grandiflora
Croton floribundus
Pseudobombax tomentosum
Macrolobium multijugum
Psidium aerugineum
Aniba guianensis
Mouriri grandiflora
Dimorphandra pullei
Calyptranthes clusiifolia
Swartzia oblata
Symmeria paniculata
Guatteria procera
Ocotea cinerea
Xylopia fruttescens
Myrcia paivae`
