name: Deploy to Dev on Merge With Main
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd sample_tracking && npm run build && firebase use staging
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entrypoint: ./sample_tracking
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RIVER_SKY_386919 }}'
          channelId: live
          projectId: river-sky-386919
